name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # プロジェクトでサポートするNode.jsのバージョン

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Puppeteer dependencies
      run: |
        # Update package lists
        sudo apt-get update
        # Install libgbm-dev, a necessary dependency for running Chrome/Chromium (used by Puppeteer)
        # in a headless environment. libgbm (Generic Buffer Management) is part of Mesa 3D Graphics Library
        # and allows buffer management without a display server.
        sudo apt-get install -y libgbm-dev

    - name: Install dependencies
      run: npm ci

    # - name: Run tests
    #   run: npm test

    - name: Install three-test-suite dependencies
      run: cd three-test-suite && npm ci

    - name: Run test suite
      run: npm run test:suite

    - name: Run repomix
      if: success() # 前のステップがすべて成功した場合のみ実行
      run: npx repomix
