name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # プロジェクトでサポートするNode.jsのバージョン

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Puppeteer dependencies
      run: sudo apt-get update && sudo apt-get install -y libgbm-dev

    - name: Install dependencies
      run: npm ci

    # - name: Run tests
    #   run: npm test

    - name: Run test suite
      run: npm run test:suite

    - name: Run repomix
      if: success() # 前のステップがすべて成功した場合のみ実行
      run: npx repomix
